### PR TITLE
chore: update seesparkbox urls to sparkbox.com

### PR DESCRIPTION
**Pull request by catheraaine**
This updates all three sites and aims to make three major changes: 

1. Change all references to seesparkbox.com to sparkbox.com 
1. Update any contact page links from the old site to the new site
1. Remove references to 123 Webster St

Also corrected a couple small typos / linter issues. 

Review each change on all sites and test that links work.

### CODE REVIEW

**Comment by catheraaine** [comment]
Footer changes: 

Screen Shot 2021-02-05 at 1 03 11 PM
Screen Shot 2021-02-05 at 1 04 02 PM

**Comment by catheraaine** [comment]
Screen Shot 2021-02-05 at 2 06 56 PM

**Comment by emilykggray** [comment]
Content is fine. I'll defer to others on design.

**Comment by catheraaine** [comment]
Updated these ! 

Screen Shot 2021-02-05 at 2 37 55 PM
Screen Shot 2021-02-05 at 2 31 16 PM

**Comment by catheraaine** [comment]
and that last commit

Screen Shot 2021-02-05 at 2 53 37 PM

**Review by mdt2 — COMMENTED** [review]
Looking good. 

/src/sections/2019/intro.mdx still has a seesparkbox reference, but I think that's the last one!

**Review by mdt2 — APPROVED** [review]
PzxwILjhjsJvnJlHFR

**Pull request merged**
